### ISSUE TITLE
Add check of end_time of clan war

### ISSUE THREAD

**Issue by dfomin** [dfomin/clashroyaledata#2]
Possible happens when clan war is not started.
```
Traceback (most recent call last):
  File "main.py", line 118, in <module>
    loop.run_until_complete(main())
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "main.py", line 106, in main
    seconds_left = await fetch_current_war(session, clan_tag)
  File "main.py", line 64, in fetch_current_war
    time_left = datetime.strptime(end_time, "%Y%m%dT%H%M%S.%fZ") - now
UnboundLocalError: local variable 'end_time' referenced before assignment
```

**Comment by dfomin** [comment]
It happened when "state" was "notInWar"
